name: CI
on:
  pull_request_target:
    branches: [ "main" ]
jobs:
  my-tests:
    runs-on: ubuntu-latest  # Specify the runner
    steps:
      # Checkout to pull request code
      - name: Checkout code
        uses: actions/checkout@v2  # Specify the version of the action
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Bash Script
        run: ./bash.sh
        env:
          TOKEN: ${{ secrets.TEST_SECRET_NAME }}  # Access the secret
