name: CI
on:
  pull_request_target:
    branches: [ "main" ]
jobs:
  my-tests:
    runs-on: ubuntu-latest  # Specify the runner (if necessary)
    steps:
      # Checkout to pull request code
      - uses: actions/checkout
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Correct indentation here

      - run: ./bash.sh
        env:
          TOKEN: ${{ secrets.TEST_SECRET_NAME }}  # Correct indentation here
