# First Workflow
name: First Workflow
on: pull_request
jobs:
  my-first-job:
    runs-on: ubuntu-latest  # Specify the runner type
    steps:
      - run: echo "; echo 'attacker controlled code here - evil and malicious'; #" > artifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt
