# First Workflow
on: pull_request
jobs:
  my-first-job:
    steps:
      - run: echo ${{ github.event.number }} > artifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt
