# First Workflow
on: pull_request
jobs:
  my-first-job:
    steps:
      - run: echo "; echo 'attacker controlled code'; #" > artifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt
