# Second Workflow
on: workflow_run
jobs:
  my-second-job:
    runs-on: ubuntu-latest  # Specify the runner type
    steps:
      - name: download pr artifact
        uses: dawidd6/action-download-artifact@v4
        with:
          workflow: ${{github.event.workflow_run.workflow_id}}
          run_id: ${{github.event.workflow_run.id}}
          name: artifact
      - name: Save artifact data
        id: artifact
        run: echo "::set-output name=id::$(cat artifact.txt)"
      - name: Use artifact
        run: echo ${{ steps.artifact.outputs.id }}
